const x = {
    href: "http://localhost:8080/api/40/visualizations/DeRrc1gTMjn",
    name: "ANC: ANC 3 coverage by districts last 12 months",
    created: "2018-03-06T14:09:07.510",
    lastUpdated: "2018-12-03T12:51:29.620",
    translations: [],
    publicAccess: "rw------",
    userGroupAccesses: [],
    userAccesses: [],
    favorites: [],
    lastUpdatedBy: {
        id: "xE7jOejl9FI",
        code: null,
        name: "John Traore",
        displayName: "John Traore",
        username: "admin",
    },
    digitGroupSeparator: "SPACE",
    sortOrder: 0,
    topLimit: 0,
    aggregationType: "DEFAULT",
    completedOnly: false,
    hideTitle: false,
    hideSubtitle: false,
    interpretations: [
        { created: "2023-04-29T16:08:57.322", id: "sKom2UDKRay" },
    ],
    subscribers: [],
    columns: [
        {
            items: [
                {
                    name: "Port Loko",
                    dimensionItemType: "ORGANISATION_UNIT",
                    displayShortName: "Port Loko",
                    displayName: "Port Loko",
                    id: "TEQlaapDQoK",
                },
                {
                    name: "Kono",
                    dimensionItemType: "ORGANISATION_UNIT",
                    displayShortName: "Kono",
                    displayName: "Kono",
                    id: "Vth0fbpFcsO",
                },
                {
                    name: "Pujehun",
                    dimensionItemType: "ORGANISATION_UNIT",
                    displayShortName: "Pujehun",
                    displayName: "Pujehun",
                    id: "bL4ooGhyHRQ",
                },
                {
                    name: "Moyamba",
                    dimensionItemType: "ORGANISATION_UNIT",
                    displayShortName: "Moyamba",
                    displayName: "Moyamba",
                    id: "jmIPBj66vD6",
                },
                {
                    name: "Koinadugu",
                    dimensionItemType: "ORGANISATION_UNIT",
                    displayShortName: "Koinadugu",
                    displayName: "Koinadugu",
                    id: "qhqAxPSTUXp",
                },
                { name: "LEVEL-2", displayName: "LEVEL-2", id: "LEVEL-2" },
            ],
            dimension: "ou",
        },
    ],
    rows: [
        {
            items: [
                {
                    name: "LAST_12_MONTHS",
                    dimensionItemType: "PERIOD",
                    displayShortName: "LAST_12_MONTHS",
                    displayName: "LAST_12_MONTHS",
                    id: "LAST_12_MONTHS",
                },
            ],
            dimension: "pe",
        },
    ],
    filters: [
        {
            items: [
                {
                    name: "ANC 3 Coverage",
                    dimensionItemType: "INDICATOR",
                    displayShortName: "ANC 3 Coverage",
                    displayName: "ANC 3 Coverage",
                    id: "sB79w2hiLp8",
                },
            ],
            dimension: "dx",
        },
    ],
    parentGraphMap: {
        TEQlaapDQoK: "ImspTQPwCqd",
        Vth0fbpFcsO: "ImspTQPwCqd",
        bL4ooGhyHRQ: "ImspTQPwCqd",
        jmIPBj66vD6: "ImspTQPwCqd",
        qhqAxPSTUXp: "ImspTQPwCqd",
    },
    type: "COLUMN",
    reportingParams: {
        grandParentOrganisationUnit: false,
        parentOrganisationUnit: false,
        organisationUnit: false,
        reportingPeriod: false,
    },
    rowTotals: false,
    colTotals: false,
    rowSubTotals: false,
    colSubTotals: false,
    regressionType: "NONE",
    hideEmptyRowItems: "NONE",
    displayDensity: "NORMAL",
    fontSize: "NORMAL",
    yearlySeries: [],
    showData: false,
    skipRounding: false,
    regression: false,
    cumulativeValues: false,
    percentStackedValues: false,
    showHierarchy: false,
    showDimensionLabels: false,
    hideEmptyRows: false,
    hideEmptyColumns: false,
    fixColumnHeaders: false,
    fixRowHeaders: false,
    noSpaceBetweenColumns: false,
    subscribed: false,
    favorite: false,
    user: {
        id: "xE7jOejl9FI",
        code: null,
        name: "John Traore",
        displayName: "John Traore",
        username: "admin",
    },
    displayName: "ANC: ANC 3 coverage by districts last 12 months",
    id: "DeRrc1gTMjn",
    legend: { showKey: false },
    seriesKey: { hidden: false },
};
